using System.Collections.Generic;
using System.Linq;
using System.Text;

namespace LSPDFREnhancedConfigurator.Services.Validation.Models
{
    /// <summary>
    /// Result of validation containing all issues found.
    /// Provides convenient querying, filtering, and summary capabilities.
    /// </summary>
    public class ValidationResult
    {
        /// <summary>
        /// Collection of all validation issues found
        /// </summary>
        public List<ValidationIssue> Issues { get; } = new List<ValidationIssue>();

        /// <summary>
        /// True if validation passed (no errors present). Warnings and advisories are allowed.
        /// </summary>
        public bool IsValid => !Issues.Any(i => i.Severity == ValidationSeverity.Error);

        /// <summary>
        /// True if any error-level issues were found
        /// </summary>
        public bool HasErrors => Issues.Any(i => i.Severity == ValidationSeverity.Error);

        /// <summary>
        /// True if any warning-level issues were found
        /// </summary>
        public bool HasWarnings => Issues.Any(i => i.Severity == ValidationSeverity.Warning);

        /// <summary>
        /// True if any advisory-level issues were found
        /// </summary>
        public bool HasAdvisories => Issues.Any(i => i.Severity == ValidationSeverity.Advisory);

        /// <summary>
        /// True if any issues were found (errors, warnings, or advisories)
        /// </summary>
        public bool HasIssues => Issues.Count > 0;

        /// <summary>
        /// Gets only error-level issues
        /// </summary>
        public IEnumerable<ValidationIssue> Errors =>
            Issues.Where(i => i.Severity == ValidationSeverity.Error);

        /// <summary>
        /// Gets only warning-level issues
        /// </summary>
        public IEnumerable<ValidationIssue> Warnings =>
            Issues.Where(i => i.Severity == ValidationSeverity.Warning);

        /// <summary>
        /// Gets only advisory-level issues
        /// </summary>
        public IEnumerable<ValidationIssue> Advisories =>
            Issues.Where(i => i.Severity == ValidationSeverity.Advisory);

        /// <summary>
        /// Gets count of error-level issues
        /// </summary>
        public int ErrorCount => Errors.Count();

        /// <summary>
        /// Gets count of warning-level issues
        /// </summary>
        public int WarningCount => Warnings.Count();

        /// <summary>
        /// Gets count of advisory-level issues
        /// </summary>
        public int AdvisoryCount => Advisories.Count();

        /// <summary>
        /// Filters issues by minimum severity threshold.
        /// Returns a new ValidationResult containing only issues at or above the specified severity.
        /// </summary>
        /// <param name="minSeverity">Minimum severity to include</param>
        public ValidationResult FilterBySeverity(ValidationSeverity minSeverity)
        {
            var filtered = new ValidationResult();
            foreach (var issue in Issues.Where(i => i.Severity >= minSeverity))
            {
                filtered.Issues.Add(issue);
            }
            return filtered;
        }

        /// <summary>
        /// Gets all issues associated with a specific rank.
        /// </summary>
        /// <param name="rankId">The rank ID to filter by</param>
        public IEnumerable<ValidationIssue> GetIssuesForRank(string rankId)
        {
            return Issues.Where(i => i.RankId == rankId);
        }

        /// <summary>
        /// Gets all issues in a specific category.
        /// </summary>
        /// <param name="category">Category to filter by (e.g., "Rank", "Vehicle", "Station")</param>
        public IEnumerable<ValidationIssue> GetIssuesByCategory(string category)
        {
            return Issues.Where(i => i.Category.Equals(category, System.StringComparison.OrdinalIgnoreCase));
        }

        /// <summary>
        /// Gets all issues generated by a specific rule.
        /// </summary>
        /// <param name="ruleId">Rule ID to filter by</param>
        public IEnumerable<ValidationIssue> GetIssuesByRule(string ruleId)
        {
            return Issues.Where(i => i.RuleId.Equals(ruleId, System.StringComparison.OrdinalIgnoreCase));
        }

        /// <summary>
        /// Gets all auto-fixable issues
        /// </summary>
        public IEnumerable<ValidationIssue> GetAutoFixableIssues()
        {
            return Issues.Where(i => i.IsAutoFixable && i.AutoFixAction != null);
        }

        /// <summary>
        /// Merges another validation result into this one.
        /// All issues from the other result are added to this result.
        /// </summary>
        /// <param name="other">The validation result to merge</param>
        public void Merge(ValidationResult other)
        {
            Issues.AddRange(other.Issues);
        }

        /// <summary>
        /// Adds a single issue to this validation result
        /// </summary>
        /// <param name="issue">The issue to add</param>
        public void AddIssue(ValidationIssue issue)
        {
            Issues.Add(issue);
        }

        /// <summary>
        /// Gets a formatted summary of all issues suitable for display to users.
        /// Includes errors, warnings, and advisories with appropriate icons and formatting.
        /// </summary>
        public string GetSummary()
        {
            if (!HasIssues)
                return "✅ No validation issues found.\n\nAll ranks have valid progression and references.";

            var summary = new StringBuilder();

            if (HasErrors)
            {
                summary.AppendLine($"❌ {ErrorCount} Error(s) Found:");
                foreach (var error in Errors.Take(10))
                {
                    summary.AppendLine($"  • {error.Message}");
                }
                if (ErrorCount > 10)
                {
                    summary.AppendLine($"  ... and {ErrorCount - 10} more error(s)");
                }
                summary.AppendLine();
            }

            if (HasWarnings)
            {
                summary.AppendLine($"⚠️ {WarningCount} Warning(s) Found:");
                foreach (var warning in Warnings.Take(10))
                {
                    summary.AppendLine($"  • {warning.Message}");
                }
                if (WarningCount > 10)
                {
                    summary.AppendLine($"  ... and {WarningCount - 10} more warning(s)");
                }
                summary.AppendLine();
            }

            if (HasAdvisories)
            {
                summary.AppendLine($"ℹ️ {AdvisoryCount} Advisory Notice(s):");
                foreach (var advisory in Advisories.Take(5))
                {
                    summary.AppendLine($"  • {advisory.Message}");
                }
                if (AdvisoryCount > 5)
                {
                    summary.AppendLine($"  ... and {AdvisoryCount - 5} more advisory notice(s)");
                }
            }

            return summary.ToString().TrimEnd();
        }

        /// <summary>
        /// Gets a compact summary line showing counts of each severity level
        /// </summary>
        public string GetCompactSummary()
        {
            if (!HasIssues)
                return "No issues";

            var parts = new List<string>();
            if (HasErrors) parts.Add($"{ErrorCount} error(s)");
            if (HasWarnings) parts.Add($"{WarningCount} warning(s)");
            if (HasAdvisories) parts.Add($"{AdvisoryCount} advisory notice(s)");

            return string.Join(", ", parts);
        }
    }
}
